### ISSUE TITLE
Can I use it for car simulation in GPU computing?

### ISSUE THREAD

**Issue by Guanyu-Lin** [wxinix/TensorFlow-Island#1]
If I understand correctly, your project enable GPU computing for External Driver Model, and Signal Control API modules in Vissim. I currently want to perform a car simulation in multi-GPUs computing, could I use your project for achieving my goal? If it is possible, could you please tell me how to use it? I would appreciate it if you could help me. Thank for your kindness and precious time.

**Comment by wxinix** [comment]
Yes you can. You would have to translate your driver behavioral model into a computational graph and let TensorFlow to run it.
